
export const CLEAR_MESSAGE = 'CLEAR_MESSAGE'; 

export const STORE_ADD_SUCCESS = 'STORE_ADD_SUCCESS'; 
export const STORE_GET_SUCCESS = 'STORE_GET_SUCCESS';
export const STORE_LOGIN_SUCCESS = 'STORE_LOGIN_SUCCESS';

export const SPOT_ADD_SUCCESS = 'SPOT_ADD_SUCCESS'; 
export const SPOT_GET_SUCCESS = 'SPOT_GET_SUCCESS';

export const CATEGORY_ADD_SUCCESS = 'CATEGORY_ADD_SUCCESS'; 
export const CATEGORY_GET_SUCCESS = 'CATEGORY_GET_SUCCESS';

export const ITEM_ADD_SUCCESS = 'ITEM_ADD_SUCCESS'; 
export const ITEM_GET_SUCCESS = 'ITEM_GET_SUCCESS';
export const ITEM_SINGLE_GET_SUCCESS = 'ITEM_SINGLE_GET_SUCCESS';

export const MEDIA_ADD_SUCCESS = 'MEDIA_ADD_SUCCESS'; 
export const MEDIA_GET_SUCCESS = 'MEDIA_GET_SUCCESS';

export const ATTRIBUTE_ADD_SUCCESS = 'ATTRIBUTE_ADD_SUCCESS'; 
export const ATTRIBUTE_GET_SUCCESS = 'ATTRIBUTE_GET_SUCCESS';

export const ORDER_ADD_SUCCESS = 'ORDER_ADD_SUCCESS'; 
export const ORDER_GET_SUCCESS = 'ORDER_GET_SUCCESS';

export const USER_ADD_SUCCESS = 'USER_ADD_SUCCESS'; 
export const USER_GET_SUCCESS = 'USER_GET_SUCCESS';

export const STATISTICS_GET_SUCCESS = 'STATISTICS_GET_SUCCESS';

export const ADMIN_ADD_SUCCESS = 'ADMIN_ADD_SUCCESS'; 
export const ADMIN_GET_SUCCESS = 'ADMIN_GET_SUCCESS';

export const HOMEPAGE_ADMIN_ADD_SUCCESS = 'HOMEPAGE_ADMIN_ADD_SUCCESS'; 
export const HOMEPAGE_ADMIN_GET_SUCCESS = 'HOMEPAGE_ADMIN_GET_SUCCESS';
export const HOMEPAGE_ADMIN_SINGLE_GET_SUCCESS = 'HOMEPAGE_ADMIN_SINGLE_GET_SUCCESS';

export const SUBPAGE_ADMIN_ADD_SUCCESS = 'SUBPAGE_ADMIN_ADD_SUCCESS'; 
export const SUBPAGE_ADMIN_GET_SUCCESS = 'SUBPAGE_ADMIN_GET_SUCCESS';

export const BLOG_ADMIN_ADD_SUCCESS = 'BLOG_ADMIN_ADD_SUCCESS'; 
export const BLOG_ADMIN_GET_SUCCESS = 'BLOG_ADMIN_GET_SUCCESS';

export const SOCIAL_ADMIN_ADD_SUCCESS = 'SOCIAL_ADMIN_ADD_SUCCESS'; 
export const SOCIAL_ADMIN_GET_SUCCESS = 'SOCIAL_ADMIN_GET_SUCCESS';

export const GALLERY_ADMIN_ADD_SUCCESS = 'GALLERY_ADMIN_ADD_SUCCESS'; 
export const GALLERY_ADMIN_GET_SUCCESS = 'GALLERY_ADMIN_GET_SUCCESS';

export const SERVER_ADD_SUCCESS = 'SERVER_ADD_SUCCESS'; 
export const SERVER_VALID_GET_SUCCESS = 'SERVER_VALID_GET_SUCCESS';
export const SERVER_WAIT_GET_SUCCESS = 'SERVER_WAIT_GET_SUCCESS';
export const SERVER_SINGLE_GET_SUCCESS = 'SERVER_SINGLE_GET_SUCCESS';

export const SERVICE_ADD_SUCCESS = 'SERVICE_ADD_SUCCESS'; 
export const SERVICE_GET_SUCCESS = 'SERVICE_GET_SUCCESS';
export const SERVICE_SINGLE_GET_SUCCESS = 'SERVICE_SINGLE_GET_SUCCESS';

export const PET_ADD_SUCCESS = 'PET_ADD_SUCCESS'; 
export const PET_GET_SUCCESS = 'PET_GET_SUCCESS';
export const PET_SINGLE_GET_SUCCESS = 'PET_SINGLE_GET_SUCCESS';

export const POST_ADD_SUCCESS = 'POST_ADD_SUCCESS'; 
export const POST_GET_SUCCESS = 'POST_GET_SUCCESS';
export const POST_SINGLE_GET_SUCCESS = 'POST_SINGLE_GET_SUCCESS';

export const ITEM_OPTION_ADD_SUCCESS = 'ITEM_OPTION_ADD_SUCCESS'; 
export const ITEM_OPTION_GET_SUCCESS = 'ITEM_OPTION_GET_SUCCESS';

export const ITEM_ORDER_GET_SUCCESS = 'ITEM_ORDER_GET_SUCCESS';
export const ITEM_ORDER_CHANGE_SUCCESS = 'ITEM_ORDER_CHANGE_SUCCESS';
export const ITEM_ORDER_SINGLE_GET_SUCCESS = 'ITEM_ORDER_SINGLE_GET_SUCCESS';
export const ITEM_ORDER_STATISTIC_GET_SUCCESS = 'ITEM_ORDER_STATISTIC_GET_SUCCESS';
export const ITEM_ORDER_SUMMARY_GET_SUCCESS = 'ITEM_ORDER_SUMMARY_GET_SUCCESS';


export const SERVICE_ORDER_GET_SUCCESS = 'SERVICE_ORDER_GET_SUCCESS';
export const SERVICE_ORDER_CHANGE_SUCCESS = 'SERVICE_ORDER_CHANGE_SUCCESS';
export const SERVICE_ORDER_SINGLE_GET_SUCCESS = 'SERVICE_ORDER_SINGLE_GET_SUCCESS';
export const SERVICE_ORDER_STATISTIC_GET_SUCCESS = 'SERVICE_ORDER_STATISTIC_GET_SUCCESS';


export const REVIEW_ADD_SUCCESS = 'REVIEW_ADD_SUCCESS'; 
export const REVIEW_GET_SUCCESS = 'REVIEW_GET_SUCCESS';

export const COUPON_ADD_SUCCESS = 'COUPON_ADD_SUCCESS'; 
export const COUPON_GET_SUCCESS = 'COUPON_GET_SUCCESS';

export const MOMENT_ADD_SUCCESS = 'MOMENT_ADD_SUCCESS'; 
export const MOMENT_GET_SUCCESS = 'MOMENT_GET_SUCCESS';
export const MOMENT_REPORT_GET_SUCCESS = 'MOMENT_REPORT_GET_SUCCESS';
export const MOMENT_SINGLE_GET_SUCCESS = 'MOMENT_SINGLE_GET_SUCCESS';

export const EXCHANGE_ADD_SUCCESS = 'EXCHANGE_ADD_SUCCESS'; 
export const EXCHANGE_GET_SUCCESS = 'EXCHANGE_GET_SUCCESS';

export const CHONFIG_ADD_SUCCESS = 'CHONFIG_ADD_SUCCESS'; 
export const CHONFIG_GET_SUCCESS = 'CHONFIG_GET_SUCCESS';

export const DELIVER_ADD_SUCCESS = 'DELIVER_ADD_SUCCESS'; 
export const DELIVER_GET_SUCCESS = 'DELIVER_GET_SUCCESS';

export const LOG_OUT = 'LOG_OUT';